### ISSUE TITLE
question for trainning result

### ISSUE THREAD

**Issue by 77SWF** [coperception/coperception#25] opened 2023-03-18 13:50 UTC
Hi, can I know the epoch numbers you choose in DiscoNet paper? I downloaded the V2X-Sim 1.0 dataset and trained model using parameters in paper, but still can't get the same result. And when I set "kd_flag" as false, I found that the AP didn't change so much compared to "kd_flag=True". I don't know if  there is something wrong when I run the code or if the version of environments have some influence on the results. 

Besides, some of the pretrained models(100 epoch) in google drive(directory checkpoints/det) get different test APs from the APs in [documentation](https://coperception.readthedocs.io/en/latest/tutorials/collaborative_models/), but others are the same. I think the test_codet.py has no errors because some results are right, but v2v and disco det pretrained model just get a low test AP. Maybe some checkpoint files are uploaded wrong?

Look forward to your reply. Thank you very much!

**Comment by dekunma** [comment] 2023-03-19 00:30
Hi, I was not the author of the DiscoNet paper, but to the best of my memory, the number of epochs was **100**. Please try if you can reproduce the result after training 100 epochs. If not, we can try to work out what would be the problem.

As for V2VNet and DiscoNet getting lower APs than expected, can I double check whether you were using V2X-Sim **2.0** dataset? The APs reported in the documentation and in [the V2X-Sim paper](https://arxiv.org/pdf/2202.08449.pdf) were all based on V2X-Sim 2.0.

**Comment by 77SWF** [comment] 2023-03-19 05:05
Thanks for your reply! 

On V2X-Sim 1.0, I have tried to train 100 epochs for both "kd_flag=True" and "kd_flag=False", the test APs are both about 57(@IoU 0.5)/51(@IoU 0.7). I checked the code for many times, and confirmed that when I setted kd_flag as true, the kd_loss did go down normally. So it confuses me that the knowledge distillation doesn't work on my machine and the APs are lower. May be I should turn to the author, thank you for your help!

As for the checkpoints provided, I did use V2X-Sim 2.0 dataset(parsed version) to test. Some of the checkpoints got the same expected APs as [documentation](https://coperception.readthedocs.io/en/latest/tutorials/collaborative_models/), such as Lower-bound, When2com and Upper-bound. Besides, I trained upper-bound myself for 100 epochs and the APs are close to [documentation](https://coperception.readthedocs.io/en/latest/tutorials/collaborative_models/). So I think there is nothing wrong with train_codet.py and test_codet.py. 

However, when testting the provided checkpoints of V2VNet and DiscoNet on V2X-Sim 2.0, I just got lower APs: DiscoNet(about 58(@IoU 0.5)/32(@IoU 0.7)), V2VNet(about 60(@IoU 0.5)/37(@IoU 0.7)). The results look very unusual, so I want to check if there is something wrong with the uploaded checkpoint files. Again I trained DiscoNet myself for 100 epochs, but the APs are still lower, about 67(@IoU 0.5)/60(@IoU 0.7). There is a warning when testing, but it seems irrelevant to the test result:
```
UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  'On January 1, 2023, MMCV will release v2.0.0, in which it will remove '
```

**Comment by dekunma** [comment] 2023-03-19 05:48
Since I have retired from the lab and lost access to the NYU High-Performance Computing cluster (where the checkpoint files were stored) for a while, it is, unfortunately, hard for me to verify if the wrong checkpoints were uploaded. Have you tried training V2VNet for 100 epochs and testing the APs? In the meanwhile, I'll look into the problem as soon as when I have time.

**Comment by 77SWF** [comment] 2023-03-19 06:11
I haven't trained V2VNet on 2.0 dataset. When I try this I'll give a feedback. Thank you all the same!

**Comment by dekunma** [comment] 2023-03-21 02:47
Hi @77SWF, I have verified that the checkpoints uploaded in Google Drive were correct.
![image](https://user-images.githubusercontent.com/53892579/226504759-d1935b0a-303b-4642-9ed8-3d134507170e.png)
I have also evaluated their performance on the V2X-Sim 2.0 dataset and found it to be consistent with what we reported in the documentation:
![image](https://user-images.githubusercontent.com/53892579/226505087-b9b05d86-e5e3-4e4d-a453-e8b233071da9.png)
![image](https://user-images.githubusercontent.com/53892579/226505248-c18afb65-d1fc-4706-b37a-83b9ddd03a1b.png)

Were you using the correct command when testing the models? For example, the command to test DiscoNet (without RSU) would be:
```
make test_no_rsu com=disco logpath='<the directory where you stored the checkpoints>'
```

Also, let me verify that we used the same testing set:
cd into the `agent0` directory of the testing set, and do `ls | grep _0` to see if the scenes you have are the same with mine:
![image](https://user-images.githubusercontent.com/53892579/226506650-d60f1130-c1e9-48bc-a4e7-3eb9cf06ac98.png)

**Comment by 77SWF** [comment] 2023-03-22 12:49
Thank you! I checked the command and testing set, and find that there are no problems. So I guessed there might be something wrong with the code ignored by me and cloned the "coperception" again and retested. Fortunately this time 2 DiscoNet checkpoints ran well and got the same results!

I might find out why my results on V2X-Sim 2.0 are different. The codes I used were cloned at the end of October 2022, and the wrong results I said above are got by this old version of codes. It seems there are many new commits I didn't notice untill your confirmation compared to the codes I used. Maybe some key changes concerning V2VNet/DiscoNet lead to the above results. 

As for the reproduced model's results, probably the same problem leads to the low APs. I'll  try again using the new version codes and try to find out what changes results in these differences. Thanks again!

**Comment by dekunma** [comment] 2023-03-22 23:55
The problem might be caused by my updates to some of the APIs. But glad that things worked out!

**Comment by simbaforrest** [comment] 2023-03-30 17:19
Thanks @dekunma! Should we close this issue?

**Comment by dekunma** [comment] 2023-03-31 02:52
@simbaforrest I think so. Let me close it now.

**Closed by dekunma** 2023-03-31 02:52 UTC
