### ISSUE TITLE
Issues while testing When2com

### ISSUE THREAD

**Issue by eyabesbes** [coperception/coperception#53] opened 2024-04-24 13:12 UTC
Hi, 
I have downloaded the checkpoints and then used them to train my model using the following command:
``  make train com=when2com rsu=0 ``
![image](https://github.com/coperception/coperception/assets/95165444/c147dd08-fde4-4d69-a340-a9414c1e16bf)

While trying to test the model using:
`` make test_no-rsu com=when2com rsu=0 wrap=0 ``
I get the following error 
![image](https://github.com/coperception/coperception/assets/95165444/e10aa149-c197-40ee-a8b3-3b48ae910dc9)
Something seem to be wrong with the inference mode.

**Comment by scdrand23** [comment] 2024-05-07 22:26
Add this line in the Makefile test block:

--inference $(inference) \

`# orginal one
test_no_rsu:
	python $(testing_script) \
	--data $(testing_data) \
	--com $(com) \
	--resume $(logpath)/$(com)/no_rsu/epoch_$(nepoch).pth \
	--tracking \
	--logpath $(logpath) \
	--apply_late_fusion $(apply_late_fusion) \
	--visualization $(visualization) \
	--rsu 0

#new one

test_no_rsu:
	python $(testing_script) \
	--data $(testing_data) \
	--com $(com) \
	--resume $(logpath)/$(com)/no_rsu/epoch_$(nepoch).pth \
	--tracking \
	--logpath $(logpath) \
	--apply_late_fusion $(apply_late_fusion) \
	--visualization $(visualization) \
	--inference $(inference) \
	--rsu 0`

**Comment by simbaforrest** [comment] 2024-06-17 16:16
Thanks @scdrand23 for answering. @eyabesbes is this still a problem? If not, I'm going to close the issue.

**Comment by simbaforrest** [comment] 2024-06-19 13:18
Closing the issue due to lack of response. Looks like the problem is addressed.

**Closed as completed by simbaforrest** 2024-06-19 13:18 UTC
